export const navbarButtonGroup = 'font-medium flex md:p-0 rounded-lg bg-transparent flex-row space-x-8 bg-transparent'
// export const navbarButton = 'block py-2 pl-5 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent'
// export const navbarButtonGroup = 'flex'
export const navbarButton = 'text-white	scroll-smooth'

export const section = 'h-auto py-10'
export const sectionTitle = 'w-full h-auto text-4xl px-10'
export const containerLg = 'w-2/3 translate-x-1/4 bg-white p-5'
export const containerMd = 'w-1/2 translate-x-1/2 bg-white'
export const containerSm = 'w-1/3 translate-x-full bg-white'
export const container = 'w-full grid grid-cols-3 gap-x-8 m-5'
export const leftIinner = 'col-span-1 text-l'
export const rightIinner = 'col-span-2 text-l'

export const skillWraper = 'mt-2 flex flex-wrap'
export const skillContainer = 'w-fit bg-blue-200 rounded-full overflow-hidden mt-2 mr-4'
export const skill = 'p-2 text-xs'

export const titleFont = 'font-bold pb-2'
export const subtitleFont = 'text-sm pb-2 font-thin	'
export const listDetailFont = 'list-disc text-sm'
